Controllers/AnimalsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zoo.Data;
using Zoo.Models;

namespace Zoo.Controllers {
    
    [Authorize]
    public class AnimalsController : Controller {

        public AnimalsController(IAnimalService animalService, UserManager<IdentityUser> userManager) {
            this.animalService = animalService;
            _userManager = userManager;
        }

        // GET: Animals
        public async Task<IActionResult> Index() {
            var user = await _userManager.GetUserAsync(User);
            return View(await animalService.All(user.Id));
        }

        public async Task<IActionResult> SpeciesFilter(string species) {
            var user = await _userManager.GetUserAsync(User); 
            return View(await animalService.FilterBySpecies(user.Id, species));
        }

        public async Task<IActionResult> GenderFilter(int gender) {
            var user = await _userManager.GetUserAsync(User); 
            return View(await animalService.FilterByGender(user.Id, gender));
        }

        // GET: Animals/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) return NotFound();

            var user = await _userManager.GetUserAsync(User);
            var animal = await animalService.Get((int) id, user.Id);

            if (animal == null) {
                return NotFound();
            }

            return View(animal);
        }

        // GET: Animals/Create
        public IActionResult Create() {
            ViewData["SpeciesId"] = new SelectList(animalService.Db.Species, "Id", "Name");
            return View();
        }

        // POST: Animals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Birthday,Gender,SpeciesId")] Animal animal) {
            var user = await _userManager.GetUserAsync(User);
            animal.IdentityUserId = user.Id;
            if (ModelState.IsValid) {
                await animalService.Insert(animal);
                return RedirectToAction(nameof(Index));
            }
            ViewData["SpeciesId"] = new SelectList(animalService.Db.Species, "Id", "Name", animal.SpeciesId);
            return View(animal);
        }

        // GET: Animals/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) return NotFound();

            var user = await _userManager.GetUserAsync(User);
            var animal = await animalService.Get((int)id, user.Id);
            if (animal == null) return NotFound();

            ViewData["SpeciesId"] = new SelectList(animalService.Db.Species, "Id", "Name", animal.SpeciesId);
            return View(animal);
        }

        // POST: Animals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Birthday,Gender,SpeciesId")] Animal animal) {
            var user = await _userManager.GetUserAsync(User);
            animal.IdentityUserId = user.Id;

            if (id != animal.Id) return NotFound();

            if (ModelState.IsValid) {
                if(await animalService.Update(animal) == true) {
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["SpeciesId"] = new SelectList(animalService.Db.Species, "Id", "Name", animal.SpeciesId);
            return View(animal);
        }

        // GET: Animals/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) return NotFound();

            var user = await _userManager.GetUserAsync(User);
            var animal = await animalService.Get((int) id, user.Id);
            if(animal == null) return NotFound();

            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var user = await _userManager.GetUserAsync(User);
            await animalService.Delete(id, user.Id);
            return RedirectToAction(nameof(Index));
        }

        private readonly IAnimalService animalService;
        private readonly UserManager<IdentityUser> _userManager;
    }
}

Controllers/SpeciesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zoo.Data;
using Zoo.Models;

namespace Zoo.Controllers {

    [Authorize]
    public class SpeciesController : Controller {

        public SpeciesController(ISpeciesService speciesService) {
            this.speciesService = speciesService;
        }

        // GET: Species
        public async Task<IActionResult> Index() {
            return View(await speciesService.All());
        }

        public async Task<IActionResult> FamilyFilter(string family) {
            return View(await speciesService.FilterByFamily(family));
        }

        public async Task<IActionResult> ContinentFilter(string continent) {
            return View(await speciesService.FilterByContinent(continent));
        }

        // GET: Species/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) return NotFound();

            var species = await speciesService.Get((int) id);

            if (species == null) return NotFound();

            return View(species);
        }

        // GET: Species/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create() {
            return View();
        }

        // POST: Species/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Family,OriginContinent,Diet")] Species species) {
            if (ModelState.IsValid) {
                await speciesService.Insert(species);
                return RedirectToAction(nameof(Index));
            }
            return View(species);
        }

        // GET: Species/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) return NotFound();

            var species = await speciesService.Get((int) id);

            if (species == null) return NotFound();

            return View(species);
        }

        // POST: Species/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Family,OriginContinent,Diet")] Species species) {
            if (id != species.Id) return NotFound();

            if (ModelState.IsValid) {
                if(await speciesService.Update(species) == true) {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(species);
        }

        // GET: Species/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) return NotFound();

            var species = await speciesService.Get((int) id);

            if (species == null) return NotFound();

            return View(species);
        }

        // POST: Species/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id){
            await speciesService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private readonly ISpeciesService speciesService;
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zoo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/app.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
</head>
<body>
    <div class="wrapper">
        <nav id="sidebar" class="sidebar">
			<div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="align-middle">Zoo</span>
                </a>
                <ul class="sidebar-nav" id="sidebar-nav">
                    <hr />
                    <li class="sidebar-header">Animals</li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Animals" asp-action="Index">
                            <span class="align-middle">Show</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Animals" asp-action="SpeciesFilter">
                            <span class="align-middle">Search by species</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Animals" asp-action="GenderFilter">
                            <span class="align-middle">Filter by gender</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Animals" asp-action="Create">
                            <span class="align-middle">Create</span>
                        </a>
                    </li>
                    <hr />
                    <li class="sidebar-header">Species</li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Species" asp-action="Index">
                            <span class="align-middle">Show</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Species" asp-action="FamilyFilter">
                            <span class="align-middle">Search by family</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Species" asp-action="ContinentFilter">
                            <span class="align-middle">Search by continent</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-area="" asp-controller="Species" asp-action="Create">
                            <span class="align-middle">Create</span>
                        </a>
                    </li>
                </ul>
			</div>
		</nav>
        <div class="main">
            <nav class="navbar navbar-expand navbar-light navbar-bg">
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav navbar-align">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </nav>
            <div class="content">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>